#!/usr/bin/env bash
# Generates frontend/.env with the deployed backend endpoints (Cognito + API).
# Reads the values from SSM Parameter Store → REQUIRES valid AWS credentials.
# Run it once after deploying (or when the User Pool / API change).
# Then `make dev` starts the frontend reading that .env, no AWS needed.
#
# Usage (default environment: test):
#   ./scripts/dev-frontend.sh        # = make dev-env
#   ENV=prod ./scripts/dev-frontend.sh

set -euo pipefail

ENV=${ENV:-test}
PROJECT={{PROJECT_NAME}}
OUT=frontend/.env

echo "→ Resolving '$ENV' endpoints from SSM"
USER_POOL_ID=$(aws ssm get-parameter --name "/${PROJECT}/${ENV}/user-pool-id" --query Parameter.Value --output text)
USER_POOL_CLIENT_ID=$(aws ssm get-parameter --name "/${PROJECT}/${ENV}/user-pool-client-id" --query Parameter.Value --output text)
API_URL=$(aws ssm get-parameter --name "/${PROJECT}/${ENV}/api-url" --query Parameter.Value --output text)

cat > "$OUT" <<EOF
# Generated by scripts/dev-frontend.sh from SSM (/${PROJECT}/${ENV}/*). Do not commit.
VITE_API_URL=${API_URL}
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
EOF

echo "✔ Wrote $OUT (ENV=$ENV). Start the frontend with: make dev"
